version: '3'
services:
  postgres:
    image: postgres:16.2
    env_file: 
      - .env
    ports:
      - '5432:5432'
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:8.6
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '15432:80'
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres: